check process graalpy with pidfile /Users/chaneychan/IdeaProjects/graalPy/conf/monit/graalpy.pid
    start program = "/usr/bin/bash /Users/chaneychan/IdeaProjects/graalPy/conf/monit/start.sh"
    stop program = "/usr/bin/bash /Users/chaneychan/IdeaProjects/graalPy/conf/monit/stop.sh"
    if 5 restarts within 5 cycles then timeout

group graalpy

set logfile /home/chaneychan/dist/log/a.log
set MAILSERVER localhost